// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHJY_LtRrn2yzk4AsvSahZSKqnd2TkLsk',
    appId: '1:1098961605624:web:012b9961815a880f5ffc0d',
    messagingSenderId: '1098961605624',
    projectId: 'micarro-ce44c',
    authDomain: 'micarro-ce44c.firebaseapp.com',
    storageBucket: 'micarro-ce44c.firebasestorage.app',
    measurementId: 'G-T54TJPQ5GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7JKOVvWsVmyO6SpQOnXYWxAcqyI2ceNk',
    appId: '1:1098961605624:android:005970635d4b21745ffc0d',
    messagingSenderId: '1098961605624',
    projectId: 'micarro-ce44c',
    storageBucket: 'micarro-ce44c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2eXd-jkVUVguE-uojrA-Skh3xMIm6sAw',
    appId: '1:1098961605624:ios:f84291f42b4c0a3e5ffc0d',
    messagingSenderId: '1098961605624',
    projectId: 'micarro-ce44c',
    storageBucket: 'micarro-ce44c.firebasestorage.app',
    iosBundleId: 'com.example.micarro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2eXd-jkVUVguE-uojrA-Skh3xMIm6sAw',
    appId: '1:1098961605624:ios:f84291f42b4c0a3e5ffc0d',
    messagingSenderId: '1098961605624',
    projectId: 'micarro-ce44c',
    storageBucket: 'micarro-ce44c.firebasestorage.app',
    iosBundleId: 'com.example.micarro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHJY_LtRrn2yzk4AsvSahZSKqnd2TkLsk',
    appId: '1:1098961605624:web:6057974e1be6a4935ffc0d',
    messagingSenderId: '1098961605624',
    projectId: 'micarro-ce44c',
    authDomain: 'micarro-ce44c.firebaseapp.com',
    storageBucket: 'micarro-ce44c.firebasestorage.app',
    measurementId: 'G-0R36ZGTTC6',
  );
}
